remote_theme: jekyll/minima
title: Steven Watson Buehler
author:
  name: Steven Buehler
  email: github_pages@swb72.us
description: >
  Gloriously awkward fifty-something.
url: "https://swbuehler72.github.io"
disqus:
  shortname: gloriously-awkward-life
minima:
  skin: auto
  nav_pages:
    - now.md
    - uses.md
  show_excerpts: false
  date_format: "%A, %-d %B %Y"
  social_links:
    - title: Steven Buehler's Facebook
      icon: facebook
      url: "https://facebook.com/stevenwatsonbuehler"
    - title: The Study of Starlight's Facebook
      icon: facebook
      url: "https://facebook.com/studyofstarlight"
    - title: TSoS YouTube
      icon: youtube
      url: "https://youtube.com/@thestudyofstarlight"
    - title: Steven's Twitter
      icon: x-twitter
      url: "https://x.com/@swb72"
    - title: The Study of Starlight on SoundCloud
      icon: soundcloud
      url: "https://soundcloud.com/thestudyofstarlight"