site: Steven Watson Buehler
url: https://swb72.us
title: Steven Watson Buehler
description: Gloriously awkward blog.
twitter:
  username: swb72
  card: summary
  creator: swb72
author:
  twitter: swb72
  name: Steven Buehler
  avatar:
  email: steven@swb72.us
  url: https://swb72.us
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"